Repository QuirkoTech/PostmanExpress, pull requests merged in 2023-12, with the labels that each got.

#149 4 digit pin
  locker_app/server/controllers/cabinetControllers.js
  organization_api/server/helpers/generateUniquePin.js
Labels: enhancement

#151 Responsive
  consumer_app/src/components/layout/Footer.jsx
  consumer_app/src/pages/ActiveParcelPage.jsx
  driver_app/src/components/layout/Footer.jsx
  driver_app/src/components/modal/Modal.jsx
  driver_app/src/pages/ActiveParcelPage.jsx
  driver_app/src/pages/AvailableParcelPage.jsx
  driver_app/src/pages/ParcelInfoPage.jsx
  locker_app/src/pages/DeliveryPage.jsx
  locker_app/src/pages/PickupPage.jsx
Labels: enhancement, development

#156 Timestamps
  consumer_app/src/components/Timestamps.jsx
  consumer_app/src/index.css
  consumer_app/src/pages/ParcelInfoPage.jsx
  organization_api/server/controllers/parcelControllers.js
  package-lock.json
Labels: bug, enhancement, development

#157 account delete modal
  consumer_app/src/components/Button.jsx
  consumer_app/src/components/auth/Authprovider.jsx
  consumer_app/src/components/layout/Header.jsx
  consumer_app/src/components/modal/DeleteModal.jsx
  consumer_app/src/components/modal/Modal.jsx
  consumer_app/src/components/modal/Overlay.jsx
  consumer_app/src/index.css
Labels: enhancement, development

#170 Done task
  consumer_app/src/components/layout/Header.jsx
  consumer_app/src/components/modal/Modal.jsx
  consumer_app/src/index.css
  consumer_app/src/pages/ActiveParcelPage.jsx
  consumer_app/src/pages/Login.jsx
  consumer_app/src/pages/NewParcelPage.jsx
  consumer_app/src/pages/ParcelHistoryPage.jsx
  consumer_app/src/pages/ParcelInfoPage.jsx
  consumer_app/src/pages/SignUp.jsx
  consumer_app/tailwind.config.js
  driver_app/src/components/NoParcelData.jsx
  driver_app/src/components/layout/Header.jsx
  driver_app/src/components/modal/Modal.jsx
  driver_app/src/pages/ActiveParcelPage.jsx
  driver_app/src/pages/AvailableParcelPage.jsx
  driver_app/src/pages/Login.jsx
  driver_app/tailwind.config.js
Labels: development

#168 Correctly representing 'from' and 'to' fields in driver app
  driver_app/src/pages/ParcelInfoPage.jsx
  organization_api/server/controllers/parcelControllers.js
Labels: bug

#173 Vitest Testing Signupform and notifications
  consumer_app/package-lock.json
  consumer_app/package.json
  consumer_app/src/components/CustomNotification.jsx
  consumer_app/src/components/index.js
  consumer_app/src/components/layout/Header.jsx
  consumer_app/src/components/layout/Layout.jsx
  consumer_app/src/index.css
  consumer_app/src/main.jsx
  consumer_app/src/pages/SignUp.jsx
  consumer_app/src/test/Notification.test.jsx
  consumer_app/src/test/Signup.test.jsx
  consumer_app/src/test/setup.js
  consumer_app/vite.config.js
Labels: development

#175 Notify receiver when parcel is ready for pickup
  organization_api/server/controllers/cabinetControllers.js
  organization_api/server/controllers/consumerControllers.js
  postmanExpressDB.sql
Labels: development

#179 Fix receiver deleted and notificate receiver when parcel delivered
  organization_api/server/controllers/consumerControllers.js
Labels: bug

#181 Fix user load
  organization_api/server/controllers/consumerControllers.js
Labels: bug
