Repository QuirkoTech/PostmanExpress, pull requests merged in 2023-11, with the labels that each got.

#2 Initialise API structure
  .env.example
  .gitignore
  consumer_app/.env.example
  consumer_app/package-lock.json
  consumer_app/package.json
  consumer_app/server/app.js
  consumer_app/server/config.js
  consumer_app/server/server.js
  driver_app/.env.example
  driver_app/.gitignore
  driver_app/package-lock.json
  driver_app/package.json
  driver_app/server/app.js
  driver_app/server/config.js
  driver_app/server/server.js
  locker_app/.env.example
  locker_app/.gitignore
  locker_app/package-lock.json
  locker_app/package.json
  locker_app/server/app.js
  locker_app/server/config.js
  locker_app/server/server.js
  package-lock.json
  package.json
  server/app.js
  server/config.js
  server/server.js
Labels: development

#3 Configure automatic deployment
  .env
  .github/workflows/run_all_apps.yml
Labels: development

#4 gitigonre not working
  .env
Labels: bug

#8 prettier dev-dep installed on root folder instead
  .prettierrc
  consumer_app/.prettierrc
  package-lock.json
  package.json
Labels: development

#7 All API starting points, GitHub actions fix
  .github/workflows/run_all_apps.yml
  consumer_app/.env.example
  consumer_app/package-lock.json
  consumer_app/package.json
  consumer_app/server/app.js
  consumer_app/server/config.js
  consumer_app/server/server.js
  driver_app/.env.example
  driver_app/package-lock.json
  driver_app/package.json
  driver_app/server/app.js
  driver_app/server/config.js
  driver_app/server/server.js
  locker_app/package-lock.json
  locker_app/package.json
  locker_app/server/app.js
  locker_app/server/config.js
  locker_app/server/server.js
  package-lock.json
  package.json
  server/app.js
  server/config.js
  server/server.js
Labels: bug, development

#13 Hotfix typo in GitHub actions file
  .github/workflows/run_all_apps.yml
Labels: bug

#14 Hotfix organization_api, removed build script
  .github/workflows/run_all_apps.yml
Labels: bug

#15 Enhanced GitHub actions file
  .github/workflows/run_all_apps.yml
Labels: development

#24 UI doc
  UI-doc.txt
Labels: documentation

#27 Frontend config
  consumer_app/src/App.jsx
  consumer_app/src/index.css
  consumer_app/tailwind.config.js
  driver_app/src/App.jsx
  driver_app/src/index.css
  driver_app/tailwind.config.js
  locker_app/src/index.css
  locker_app/tailwind.config.js
Labels: development

#28 Fix actions file
  .github/workflows/run_all_apps.yml
Labels: bug

#29 Api doc
  API-doc.md
  UI-doc.txt
Labels: documentation

#32 Fix API configuration
  .github/workflows/run_all_apps.yml
  consumer_app/package.json
  consumer_app/server/config.js
  driver_app/package.json
  driver_app/server/config.js
  locker_app/package.json
  locker_app/server/config.js
  organization_api/package.json
  organization_api/server/config.js
Labels: bug

#43 Actions test
  .github/workflows/run_all_apps.yml
Labels: bug

#44 Package lock ignore
  .gitignore
  consumer_app/package-lock.json
  driver_app/package-lock.json
  locker_app/package-lock.json
  organization_api/package-lock.json
  package-lock.json
Labels: bug

#48 Get back lock file
  .github/workflows/run_all_apps.yml
  .gitignore
  consumer_app/package-lock.json
  driver_app/package-lock.json
  locker_app/package-lock.json
  organization_api/package-lock.json
  package-lock.json
Labels: bug

#51 Consumer login api
  .github/workflows/run_all_apps.yml
  API-doc.md
  API_documentation_for_frontend.md
  consumer_app/.env.example
  consumer_app/.eslintrc.cjs
  consumer_app/package-lock.json
  consumer_app/package.json
  consumer_app/public/favicon-512.png
  consumer_app/server/app.js
  consumer_app/server/controllers/authControllers.js
  consumer_app/server/controllers/errorControllers.js
  consumer_app/server/helpers/APIError.js
  consumer_app/server/helpers/catchAsync.js
  consumer_app/server/helpers/checkContentType.js
  consumer_app/server/helpers/hashPwd.js
  consumer_app/server/helpers/protect.js
  consumer_app/server/helpers/sendRequestToOrgAPI.js
  consumer_app/server/routes/authRoutes.js
  db.sql
  driver_app/.env.example
  driver_app/.eslintrc.cjs
  driver_app/public/favicon-512.png
  driver_app/server/app.js
  driver_app/server/db.js
  locker_app/.eslintrc.cjs
  locker_app/public/favicon-512.png
  organization_api/.env.example
  organization_api/package-lock.json
  organization_api/package.json
  organization_api/server/app.js
  organization_api/server/controllers/consumerControllers.js
  organization_api/server/controllers/errorController.js
  organization_api/server/db.js
  organization_api/server/helpers/APIError.js
  organization_api/server/helpers/catchAsync.js
  organization_api/server/helpers/protect.js
  organization_api/server/helpers/signTokens.js
  organization_api/server/routes/consumerRoutes.js
  organization_api/server/routes/parcelRoutes.js
Labels: development

#71 User parcels
  API_documentation_for_frontend.md
  consumer_app/server/app.js
  consumer_app/server/controllers/userControllers.js
  consumer_app/server/routes/userRoutes.js
  db.sql
  organization_api/server/controllers/consumerControllers.js
  organization_api/server/routes/consumerRoutes.js
Labels: development

#91 Consumer parcel history
  API_documentation_for_frontend.md
  consumer_app/server/controllers/userControllers.js
  consumer_app/server/routes/userRoutes.js
  driver_app/server/controllers/authControllers.js
  organization_api/server/controllers/consumerControllers.js
  organization_api/server/controllers/parcelControllers.js
  organization_api/server/routes/consumerRoutes.js
Labels: development

#88 Log outs
  API_documentation_for_frontend.md
  consumer_app/server/app.js
  consumer_app/server/controllers/authControllers.js
  consumer_app/server/controllers/userControllers.js
  consumer_app/server/frontend-test/index.html
  consumer_app/server/frontend-test/index.js
  consumer_app/server/routes/userRoutes.js
  driver_app/server/app.js
  driver_app/server/controllers/authControllers.js
  driver_app/server/routes/authRoutes.js
  locker_app/server/app.js
  organization_api/server/app.js
  organization_api/server/controllers/consumerControllers.js
  organization_api/server/controllers/parcelControllers.js
  organization_api/server/helpers/protect.js
  organization_api/server/routes/consumerRoutes.js
  postmanExpressDB.sql
Labels: development

#97 Logout consumer app
  consumer_app/.eslintrc.cjs
  consumer_app/src/components/modal/Modal.jsx
  consumer_app/src/pages/NewParcelPage.jsx
Labels: development

#100 Better consumer delete
  organization_api/server/controllers/consumerControllers.js
  organization_api/server/controllers/parcelControllers.js
  organization_api/server/helpers/protect.js
  postmanExpressDB.sql
Labels: bug

#105 Driver load
  API_documentation_for_frontend.md
  driver_app/server/app.js
  driver_app/server/controllers/driverControllers.js
  driver_app/server/routes/authRoutes.js
  driver_app/server/routes/driverRoutes.js
  organization_api/server/controllers/parcelControllers.js
  organization_api/server/routes/parcelRoutes.js
Labels: development

#122 Added limiter to API requests
  consumer_app/package-lock.json
  consumer_app/package.json
  consumer_app/server/helpers/limiters.js
  consumer_app/server/helpers/sendRequestToOrgAPI.js
  consumer_app/server/routes/authRoutes.js
  consumer_app/server/routes/parcelRoutes.js
  consumer_app/server/routes/userRoutes.js
  consumer_app/test/api_test.js
  driver_app/package-lock.json
  driver_app/package.json
  driver_app/server/app.js
  driver_app/server/controllers/authControllers.js
  driver_app/server/controllers/parcelControllers.js
  driver_app/server/helpers/limiters.js
  driver_app/server/helpers/sendRequestToOrgAPI.js
  locker_app/package-lock.json
  locker_app/package.json
  locker_app/server/app.js
  locker_app/server/helpers/limiters.js
  locker_app/server/helpers/sendRequestToOrgAPI.js
  organization_api/server/controllers/cabinetControllers.js
  organization_api/server/controllers/consumerControllers.js
  organization_api/server/controllers/parcelControllers.js
  organization_api/server/db.js
  organization_api/server/routes/consumerRoutes.js
Labels: bug, enhancement, development

#131 API fixes
  consumer_app/server/helpers/limiters.js
  consumer_app/server/routes/parcelRoutes.js
  consumer_app/test/api_test.js
  driver_app/server/helpers/limiters.js
  driver_app/server/helpers/sendEmail.js
  locker_app/server/helpers/limiters.js
  organization_api/server/controllers/consumerControllers.js
  organization_api/server/controllers/parcelControllers.js
  organization_api/server/helpers/compareDriverAndParcelLocations.js
  organization_api/server/helpers/driverCanAcceptParcel.js
  organization_api/server/helpers/sendEmail.js
Labels: bug

#134 Driver app connecting UI with API. Layout fixes and changes
  consumer_app/src/constants/index.js
  consumer_app/src/pages/ActiveParcelPage.jsx
  driver_app/package-lock.json
  driver_app/package.json
  driver_app/src/components/Button.jsx
  driver_app/src/components/Spinner.jsx
  driver_app/src/components/index.js
  driver_app/src/components/layout/Header.jsx
  driver_app/src/components/layout/Layout.jsx
  driver_app/src/index.css
  driver_app/src/pages/ActiveParcelPage.jsx
  driver_app/src/pages/AvailableParcelPage.jsx
  driver_app/src/pages/ParcelInfoPage.jsx
  driver_app/src/utils/index.js
  driver_app/tailwind.config.js
  postmanExpressDB.sql
Labels: development
